## This file will run the tests for the functions in the files -
#  numeric_derivative.py, rmse.py, & tensor_derivative.py
# For these 3 files, there are test files created named - 
#  numeric_derivative_test.py, rmse_test.py, & tensor_derivative_test.py

## Code for testing first 3 files using the later 3 files:
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test numeric_derivation.py
      run: |
        python -m pytest numeric_derivation_test.py
    - name: Test rmse.py
      run: |
        python -m pytest rmse_test.py
    - name: Test tensor_multiplication.py
      run: |
        python -m pytest tensor_multiplication_test.py
